# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-06 08:38
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30)),
                ('verify_code', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('phone', models.CharField(max_length=11)),
                ('username', models.CharField(max_length=30)),
                ('verify_code', models.CharField(max_length=6)),
                ('status', models.CharField(max_length=10)),
                ('send_time', models.DateTimeField(default=datetime.datetime.now)),
            ],
        ),
    ]
